services:
  - type: web
    name: depov3
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn depov3.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: depov3_db
          property: connectionString

databases:
  - name: depov3_db
    databaseName: depov3
    user: depov3 