# Generated by Django 5.0.2 on 2025-03-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='code',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Tedarikçi Kodu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_number',
            field=models.CharField(default=1, max_length=20, verbose_name='Vergi Numarası'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_office',
            field=models.CharField(default=1, max_length=100, verbose_name='Vergi Dairesi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='unit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
